### ISSUE TITLE
feat(lib): allow users to use custom conventions

### ISSUE THREAD

**Issue by PascalPrecht** [clog-tool/clog-cli#59]
@vyp [came up](https://github.com/thoughtram/clog/issues/57#issuecomment-120971614) with the great point of allowing users to define custom conventions that can be consumed by `clog`.

This issue should help us discussing this feature and how we want to implement it. It's clear that we need an AST in order to understand any convention, but therefore we also need a lexer/tokenizer that consumes a [context free grammar](http://www.ps.uni-saarland.de/~niehren/oz-natural-language-script.html/vorlesung/node49.html) that is defined by the user.

I'll think about what it could look like from a user perspective when hooking up a custom convention. Any thoughts regarding this implementation are very welcome!

**Comment by kbknapp** [comment]
The current functionality almost allows this. We're pretty liberal with what the posibilities are already. For example (and this isn't directed at @PascalPrecht , just in general :) ), our current commit message is pretty lose:

```
<SECTION_TRIGGER>[(COMPONENT)]<:><MESSAGE>

[BODY]

[Closes|breaks][#]
```

Where there are only three *required* items, `section_trigger` (aka `alias`, which determines which "section" the commit applies to), a `:` to separate the section_trigger (and optional `component`) from the commit message, and a `message`. 

We already allow completely custom sections, etc. 

Because of the way changelogs are written/coupled with finding appropriate commits, I'm not sure of how to allow pure custom conventions outside of the "rules" we've set. I.e. We use those rules to translate a commit message to and write:

```
<SECTION>
    * [COMPONENT [\n\t * ]] <MESSAGE> (<commit> [, [Closes #] ])
```

In order to define a truly custom grammar, the user would have to specify not only a regex to grab commits, but also some sort of closure to take those commits and write them out as well...which is almost like providing a custom re-write of `clog`. Not saying it's not doable, but I guess I'd need a more concrete example of what exactly someone would like to be able to do that they can't with the current "rules."

**Comment by vyp** [comment]
Sorry for the late reply guys. I think @PascalPrecht may have misunderstood my comment. I was talking about supporting the idea of an internal ast, or JSON output (or both) so that it can probably be pretty easy to render various "formats". So formats being markdown (already done), html, the gnu changelog thing I was talking about, etc etc.

When I quoted "conventional" in that comment in the last line, I was just referring to the "conventional" commit messages we are already using. i.e `feat(scope): one line summary`. Not that I wanted a fully flexible way of doing a whole different type of commit message. And as @kbknapp, the current functionality is already pretty flexible because @kbknapp implemented the custom sections that can be user defined.

In fact, I think we *should* stick to this "convention" of commit messages, not only does it make the code much simpler, but it's just overall less confusing to only support one single commit message format.

So to clarify again, I'm good with one single *commit message format* (i.e. what you type in `git commit`), but I'm also good with having various *output formats* (i.e. the format of the final changelogs themselves markdown, html, json etc.) as suggested in #57.

I'm quoting "convention" everywhere as a reference to the [angular js git commit message guidelines](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit), in assumption of the fact that they were the ones who invented the whole `type(scope): subject` thing right? But also to acknowledge that I understand that it isn't exactly much of a "convention" yet (i.e. widely used).

**Comment by cburgdorf** [comment]
>In order to define a truly custom grammar, the user would have to specify not only a regex to grab commits, but also some sort of closure to take those commits and write them out as well...which is almost like providing a custom re-write of clog.

I feel the same about this issue. I think an internal AST would be great to support different *output* formats but I don't think we can easily support different *input* formats.
