### ISSUE TITLE
quesion: split repo into lib and cli

### ISSUE THREAD

**Issue by PascalPrecht** [clog-tool/clog-cli#70]
As far as I can see, the code base is already structured and spit into library and cli code. Now that we moved the code to this organisation, we could also consider having a dedicated cli and lib repo.

Thoughts?

**Comment by kbknapp** [comment]
I am in favor of this primarily because a change to one portion would then not require a new release of the other. Currently, a change to the CLI would require a whole new release, which `libclog` users may not care about.

Like you (@PascalPrecht) said, everything is already pretty much split, so it would be an easy change. One notable portion that isn't *quite* split is `Clog::from_matches` which should move to the CLI, and may require minor changes to it....shouldn't be a big deal or difficult at all.

One other question this brings up, which would get the `clog` name?

CLI: `clog-cli` (?)
LIB: `clog`

**OR**

CLI: `clog`
LIB: `libclog` (?)

**Comment by vyp** [comment]
@kbknapp I'd expect *most* visitors would want to use the cli program right? So would it be reasonable to suggest that the cli one should get the `clog` name?

**Comment by PascalPrecht** [comment]
Let me throw in some more suggestions:

- clog.rs (indicating that this is a rust lib)
- cli (just cli because we know we are in the clog org)

Or

- clog-lib
- clog-cli

Or really just

- clog
- clog-cli


I think it'd be good to have "cli" in the name of the cli repo.

**Comment by cburgdorf** [comment]
I would say that the executable that people use to generate changelogs should be named `clog`. But technically speaking the executable is the CLI. So the question is: Would it be acceptable to have the repo named `clog-cli` while the binary is named `clog`?

**Comment by kbknapp** [comment]
Actually yeah that's a good idea. Name the repos `clog-cli` and `clog-lib` but the binary (for the cli) will be `clog` and the crate (for the lib) which will be uploaded to crates.io will also be `clog`. I don't believe we could upload the binary (cli crate) to crates.io using this convention, but that shouldn't be an issue. 

Another upside to this separation is they can have independent deps.

**Comment by cburgdorf** [comment]
>I don't believe we could upload the binary (cli crate) to crates.io using this convention, but that shouldn't be an issue.

Not sure if I'm following. For crates.io, the name of the repository shouldn't be important, right? It would simply be a crate called `clog` hosted in a repository called `clog-cli`, no?

But if I understand you correctly, you wouldn't upload the executable to crates.io at all, right? Has this any downside? Is crates.io absolutely useless for executables?

I guess if we both crates have the same name, we would have to alias the libary crate inside the CLI crate to use it, right? I mean something like `extern crate clog as clog_lib` (not sure if that's the right syntax).

**Comment by cburgdorf** [comment]
Ah, you mean crates.io wouldn't allow to crates with the same name, I guess? I'm still wondering if there's any downside of not having the executable on crates.io. I could imagine that it becomes more common to put executables on crates.io when we get a `cargo install` command. People may just use it to install useful executables via crates.io.

**Comment by kbknapp** [comment]
Yep you're exactly right on all points!

Like you said, the only downside to not uploading the cli to crates.io is
if a `cargo install` uses it for binaries. Since there isn't currently a
`cargo install` the point is somewhat moot, and there isnt really a reason
to upload binary only crates to crates.io :P

**Comment by cburgdorf** [comment]
But `cargo install` is in the making if I'm not mistaking ;)

**Comment by kbknapp** [comment]
[Yep](https://github.com/rust-lang/rfcs/pull/1200) but I'm unsure how the
final implementation will work. I haven't looked much at it.

**Comment by kbknapp** [comment]
Even in the case where we do want to upload the cli to crates.io I think it would be easier to re-name the cli package to `clog-cli` (but the produced binary will still be `clog`) because libs in Rust get auto-named `lib<crate_name>.rlib` so calling the lib `clog-lib` would end up producing a `libclog_lib.rlib` which looks silly....but it doesn't actually hurt anything :P also *using* the crate would require a few extra keystrokes unless you re-name on use.

**Comment by PascalPrecht** [comment]
Let's go with clog-cli and clog-lib then.

**Comment by kbknapp** [comment]
@cburgdorf If you're good with this, I'll go about splitting them off and create a new `clog-lib` repo, as well as re-naming this one to `clog-cli`. Once that's done I think it'd be a good point to put out a 0.9.0 release as well (related to #71 )

**Comment by cburgdorf** [comment]
:+1:  let's do so

**Comment by PascalPrecht** [comment]
@kbknapp doesn't it make more sense to rename this to clog-lib and create the clog-cli repo? Because then we really just have to pull stuff out.

**Comment by kbknapp** [comment]
> doesn't it make more sense to rename this to clog-lib and create the clog-cli repo? Because then we really just have to pull stuff out.

Kind of, but it's not too much work (I'm actually working on it now :wink:). Plus this repo started as the CLI...so I was just sticking with it :)

**Comment by kbknapp** [comment]
[clog-lib] should now be good to go. Once I pair down this repo to just `clog-cli` I'll test it to ensure everything is working good before we upload to crates.io or release a new version.

**Comment by kbknapp** [comment]
Ive git everything split out, but I'm going to run it through some tests before pushing it here. I'll do that tonight when I get home, then this should be closed :)

**Comment by kbknapp** [comment]
Everything appears to be working! @cburgdorf if you could publish a new version of [clog-lib](https://github.com/clog-tool/clog-lib) to crates.io I will then change the `clog` dep of `clog-cli` from the git repo to crates.io.

**Comment by cburgdorf** [comment]
It's published. I also made you a co-owner of that crate.

**Comment by kbknapp** [comment]
Awesome! I'll make the switch when I get home if its not already done by that time :wink:

**Comment by cburgdorf** [comment]
Fixed ;) https://github.com/clog-tool/clog-cli/commit/c18fade5a1ba00ee86b2c25da61c1ff7aadbf829

**Comment by kbknapp** [comment]
:+1:
