### ISSUE TITLE
Empty  changelog

### ISSUE THREAD

**Issue by fedexin40** [clog-tool/clog-cli#85]
Hello everybody @kbknapp 

I am not sure what i am doing wrong. I use Arch Linux and i have installed clog-git from the AUR, I have proved too with git-bin but the result is the same. 

After execute
```
clog -r https://github.com/clog-tool/clog-cli --outfile only_new.md
```

I always obtain  a file with only two lines
[only_new.md.zip](https://github.com/clog-tool/clog-cli/files/161874/only_new.md.zip)

Could someone help me to find out where is my mistake?

Thanks in advance

**Comment by kbknapp** [comment]
This is because the `clog-cli` repo has `clog` configuration file in it which states to only only pick up commits from the latest tag (of which there have been none yet). That file makes it so that you don't have to use all the command line options each time you run `clog` (such as `-r <repo>` or `--outfile <file>`, etc.)

Delete `.clog.toml` and re-run and you should see all the commits in the change log :wink:

**Comment by fedexin40** [comment]
Thanks @kbknapp it worked :+1:

**Comment by cburgdorf** [comment]
Closing here. Feel free to reopen.
